### ISSUE TITLE
Release 2.12, 2.11

### ISSUE THREAD

**Issue by borissmidt** [Treev-io/tagged-types#4]
Dear Tvaroh,

It seems you had support for 2.12 in release 3.5.1.
But dropped it after 3.6.0 after merging the PR i've made.
Would you be so kind to release it for 2.12 and maybe 2.11 if that is possible.
(our company just started to migrate to 2.13 so i can't use it yet)

**Comment by Tvaroh** [comment]
Hey @borissmidt - thanks for reporting. I've just published a follow-up release: https://repo1.maven.org/maven2/io/treev/tagged-types_2.12/3.6.1/

**Comment by borissmidt** [comment]
Thx!
